 [build]
  command = "npm run build" # Adjust to your actual build command
  publish = "dist" # Replace with your output folder if different (e.g., public, build)

[[redirects]]
  from = "/api/*"
  to = "https://newsapi.org/v2/:splat"
  status = 200
  force = true
