# File: netlify.toml

[build]
  publish = "dist" # Adjust this to the folder containing your static files
  command = "npm run build" # Adjust based on your project setup

[[redirects]]
  from = "/api/*"
  to = "https://newsapi.org/:splat" # Redirect API requests to the NewsAPI server
  status = 200
  force = true
