 [build]
  command = "" # No build command needed
  publish = "dist" # The folder containing your HTML, CSS, and JS files

[[redirects]]
  from = "/api/*"
  to = "https://newsapi.org/v2/:splat"
  status = 200
  force = true
