 [build]
  command = ""  # No build command needed for static files
  publish = "."  # Point to the root directory

[[redirects]]
  from = "/api/*"
  to = "https://newsapi.org/v2/:splat"
  status = 200
  force = true
