 [build]
  command = ""  # No build command needed for static files
  publish = "."  # Point to the root directory where your files are

[[redirects]]
  from = "/api/*"
  to = "https://newsapi.org/v2/:splat"
  status = 200
  force = true
  headers = { "Cache-Control" = "no-cache" }
